[env:m5stack-cardputer]
platform = espressif32
board = m5stack-stamps3
framework = arduino
lib_deps =
    m5stack/M5Cardputer@^1.0.2
    bblanchon/ArduinoJson@^7.0.0
    links2004/WebSockets@^2.4.0
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DUSER_WIFI_SSID=\"${sysenv.M5CLAW_WIFI_SSID}\"
    -DUSER_WIFI_PASS=\"${sysenv.M5CLAW_WIFI_PASS}\"
    -DUSER_LLM_KEY=\"${sysenv.M5CLAW_LLM_KEY}\"
    -DUSER_LLM_PROVIDER=\"${sysenv.M5CLAW_LLM_PROVIDER}\"
    -DUSER_LLM_MODEL=\"${sysenv.M5CLAW_LLM_MODEL}\"
    -DUSER_DS_KEY=\"${sysenv.M5CLAW_DS_KEY}\"
    -DUSER_CITY=\"${sysenv.M5CLAW_CITY}\"
    -DUSER_LLM_HOST=\"${sysenv.M5CLAW_LLM_HOST}\"
    -DUSER_LLM_PATH=\"${sysenv.M5CLAW_LLM_PATH}\"
extra_scripts = pre:load_config.py
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.filesystem = spiffs
