// Auto-generated by resolve_dns.py — do not edit manually
// Re-run: python resolve_dns.py
#pragma once
#include <WiFi.h>

struct DnsCacheEntry { const char* host; const char* ip; };

static const DnsCacheEntry DNS_CACHE[] = {
    {"api.minimaxi.com", "198.18.3.63"},
    {"api.anthropic.com", "198.18.3.64"},
    {"api.openai.com", "198.18.3.65"},
    {"open.feishu.cn", "198.18.2.18"},
    {"msg-frontier.feishu.cn", "198.18.3.70"},
    {"open.bigmodel.cn", "198.18.3.66"},
    {"dashscope.aliyuncs.com", "198.18.3.67"},
    {"geocoding-api.open-meteo.com", "198.18.3.68"},
    {"api.open-meteo.com", "198.18.3.69"},
    {"pool.ntp.org", "198.18.3.71"},
    {nullptr, nullptr}
};

static bool cachedResolve(const char* host, IPAddress& ip) {
    for (int i = 0; DNS_CACHE[i].host; i++) {
        if (strcmp(host, DNS_CACHE[i].host) == 0) {
            if (ip.fromString(DNS_CACHE[i].ip)) return true;
            break;
        }
    }
    if (WiFi.status() != WL_CONNECTED) return false;
    return WiFi.hostByName(host, ip);
}
